name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t wish-app .

    - name: Save Docker image to tar file
      run: docker save wish-app > wish-app.tar

    - name: Check if TAR file exists
      run: ls -al

    - name: Copy TAR to Server via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: wish-app.tar
        target: /home/ubuntu/bokgi

    - name: Run WishService on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop wish-app || true
          sudo docker rm wish-app || true
          sudo docker load < /home/ubuntu/bokgi/wish-app.tar
          sudo docker run -d --name wish-app --network my-network -p 8082:8082 wish-app
